server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

logging:
  level:
    root: info

app:
  dir:
    imgdir: file://c:/hanaspring/sb2/imgs
    logdir: file://c:/hanaspring/sb2/logs